# Generated by Django 3.2.5 on 2022-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upimage',
            name='img',
            field=models.ImageField(blank=True, upload_to='upimg/'),
        ),
    ]
